// src/app/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл', flag: '🇲🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
];

export interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}export const translations: Translations = {
  en: {
    welcome: 'Welcome back, {name}!',
    dashboardSubtitle: 'Here\'s what\'s happening with your competitions today.',
    activeCompetitions: 'Active Competitions',
    totalJudges: 'Total Judges',
    submissionsToday: 'Submissions Today',
    averageScore: 'Average Score',
    noCompetitions: 'No competitions available.',
    selectLanguage: 'Select Language',
    retry: 'Retry',
    comingSoon: 'More dashboard features coming soon!',
    participants: 'Participants',
    judges: 'Judges',
    ends: 'Ends',
    back: 'Back',
    judgePanel: 'Judge Panel',
    welcomeJudge: 'Welcome Judge, {name}!',
    competition: 'Competition',
    upcoming: 'Upcoming',
    timeTBD: 'Time TBD',
    noPerformance: 'No Performance',
    scoring: 'Scoring',
    totalScore: 'Total Score',
    criteria_criteria1: 'Criteria 1',
    criteria_criteria2: 'Criteria 2',
    criteria_criteria3: 'Criteria 3',
    weight: 'Weight: {value}',
    scoreLabel: 'Score',
    poor: 'Poor',
    average: 'Average',
    excellent: 'Excellent',
    commentsLabel: 'Comments',
    commentPlaceholder: 'Add a comment for {criteria}',
    clearScores: 'Clear Scores',
    submitScores: 'Submit Scores',
    leaderboard: "Leaderboard",
    realTimeCompetitionResults: "Real-time competition results",
    live: "LIVE",
    refresh: "Refresh",
    selectEvent: "Select Event",
    progress: "Progress",
    completed: "Completed",
    totalTeams: "Total Teams",
    judged: "Judged",
    hackathon2023Rankings: "Hackathon 2023 Rankings",
    devSprint2025Rankings: "DevSprint 2025 Rankings",
    aiChallenge2024Rankings: "AI Challenge 2024 Rankings",
    team: "Team",
    performance: "Performance",
    waitingForMoreTeams: "Waiting for {count} more teams to be judged...",
    unknown: "Unknown",
    failedFetchCompetitions: "Failed to fetch competitions: {status}",
    failedFetchScoreboard: "Failed to fetch scoreboard: {status}",
    invalidResponseFormat: "Invalid response format",
    noCompetitionsAvailable: "No competitions available",
    noScoresAvailable: "No scores available",
    errorTitle: "Error",
    unknownError: "An unknown error occurred",
    backToDashboard: "Back to Dashboard",
    competitionManagement: "Competition Management",
    manageExistingCompetitions: "Manage existing competitions",
    allCompetitions: "All Competitions",
    createCompetition: "Create Competition",
    hackathon2023: "Hackathon 2023",
    annualCodingCompetition: "Annual coding competition",
    devSprint2025: "DevSprint 2025",
    rapidSoftwareDevContest: "24-hour rapid software dev contest",
    aiChallenge2024: "AI Challenge 2024",
    buildInnovativeAIModels: "Build innovative AI models",
    viewDetails: "View Details",
    backToList: "Back to List",
    createNewCompetition: "Create New Competition",
    competitionName: "Competition Name",
    status: "Status",
    description: "Description",
    startDate: "Start Date",
    endDate: "End Date",
    judgingCriteria: "Judging Criteria",
    addCriteria: "Add Criteria",
    criterionName: "Criterion Name",
    addParticipant: "Add Participant",
    addJudge: "Add Judge",
    judgeName: "Judge Name",
    judgeEmail: "Judge Email",
    totalWeight: "Total Weight: {value}%",
    totalMustBe100: "Total must be 100%",
    noCompetitionsYet: "No competitions yet",
    getStartedCreateCompetition: "Get started by creating a new competition",
    accessDenied: "Access Denied",
    onlyAdmins: "Only admins can access this page",
    invalidInput: "Invalid Input",
    competitionNameRequired: "Competition name is required",
    invalidCriteria: "Invalid Criteria",
    criteriaNameWeightRequired: "Each criterion must have a name and a weight greater than 0",
    totalWeightMustBe100: "Total weight of criteria must be 100%",
    invalidDates: "Invalid Dates",
    startDateBeforeEndDate: "Start date must be before end date",
    validDatesRequired: "Please provide valid start and end dates",
    participantNameRequired: "Participant name is required",
    judgeNameEmailRequired: "Judge name and email are required",
    invalidEmail: "Please enter a valid email address",
    cannotRemove: "Cannot Remove",
    atLeastOneCriterion: "At least one criterion is required",
    success: "Success",
    competitionCreated: "Competition created successfully!",
    competitionDeleted: "Competition deleted successfully!",
    error: "Error",
    couldNotCreateCompetition: "Could not create competition",
    couldNotDeleteCompetition: "Could not delete competition",
    confirmDelete: "Are you sure you want to delete this competition?",
    unnamedCompetition: "Unnamed Competition",
    unnamedParticipant: "Unnamed Participant",
    unnamedJudge: "Unnamed Judge",
    noDescription: "No description provided",
    enterCompetitionName: "Enter competition name",
    enterDescription: "Enter competition description",
    enterParticipantName: "Enter participant name",
    enterJudgeName: "Enter judge name",
    enterJudgeEmail: "Enter judge email",
    enterCriterionName: "Enter criterion name",
    dashboard: "Dashboard",
    judge: "Judge",
    scoreboard: "Scoreboard",
    competitions: "Competitions",
    profile: "Profile",
    logout: "Logout",
    toggleMenu: "Toggle Menu",
    closeMenu: "Close Menu",
    openMenu: "Open Menu",
    profileImageAlt: "Profile Image",
    logoAlt: "JudgeHub Logo",
    roleAdmin: "Admin",
    roleJudge: "Judge",
    roleViewer: "Viewer",
    unknownUser: "Unknown User",
    unknownRole: "Unknown Role",
    login: "Login",
  },
  mn: {
    welcome: 'Тавтай морил, {name}!',
    dashboardSubtitle: 'Таны өрсөлдөөний талаарх өнөөдрийн мэдээлэл энд байна.',
    activeCompetitions: 'Идэвхтэй тэмцээнүүд',
    totalJudges: 'Нийт шүүгчид',
    submissionsToday: 'Өнөөдрийн өргөдөл',
    averageScore: 'Дундаж оноо',
    noCompetitions: 'Тэмцээн байхгүй байна.',
    selectLanguage: 'Хэл сонгох',
    retry: 'Дахин оролдох',
    comingSoon: 'Удахгүй илүү олон боломжууд нэмэгдэнэ!',
    participants: 'Оролцогчид',
    judges: 'Шүүгчид',
    ends: 'Дуусах',
    back: 'Буцах',
    judgePanel: 'Шүүгчийн Хяналтын Самбар',
    welcomeJudge: 'Тавтай морил, Шүүгч {name}!',
    competition: 'Тэмцээн',
    upcoming: 'Удахгүй болох',
    timeTBD: 'Цаг тодорхойгүй',
    noPerformance: 'Гүйцэтгэл байхгүй',
    scoring: 'Оноо өгөх',
    totalScore: 'Нийт Оноо',
    criteria_criteria1: 'Шалгуур 1',
    criteria_criteria2: 'Шалгуур 2',
    criteria_criteria3: 'Шалгуур 3',
    weight: 'Жин: {value}',
    scoreLabel: 'Оноо',
    poor: 'Муу',
    average: 'Дундаж',
    excellent: 'Маш сайн',
    commentsLabel: 'Сэтгэгдэл',
    commentPlaceholder: '{criteria}-д зориулсан сэтгэгдэл нэмнэ үү',
    clearScores: 'Оноог Арилгах',
    submitScores: 'Оноог Илгээх',
    leaderboard: "Онооны Самбар",
    realTimeCompetitionResults: "Бодит цагийн тэмцээний үр дүн",
    live: "ШУУД",
    refresh: "Сэргээх",
    selectEvent: "Арга хэмжээ сонгох",
    progress: "Ахиц",
    completed: "Дууссан",
    totalTeams: "Нийт Багууд",
    judged: "Шүүгдсэн",
    hackathon2023Rankings: "Хакатон 2023-ын Зэрэглэл",
    devSprint2025Rankings: "ДевСпринт 2025-ын Зэрэглэл",
    aiChallenge2024Rankings: "AI-ийн Сорилт 2024-ын Зэрэглэл",
    team: "Баг",
    performance: "Гүйцэтгэл",
    waitingForMoreTeams: "{count} багыг шүүхыг хүлээж байна...",
    unknown: "Тодорхойгүй",
    failedFetchCompetitions: "Тэмцээнүүдийг татаж авж чадсангүй: {status}",
    failedFetchScoreboard: "Онооны самбарыг татаж авж чадсангүй: {status}",
    invalidResponseFormat: "Хүчингүй хариуны формат",
    noCompetitionsAvailable: "Тэмцээн байхгүй байна",
    noScoresAvailable: "Оноо байхгүй байна",
    errorTitle: "Алдаа",
    unknownError: "Тодорхойгүй алдаа гарлаа",
    backToDashboard: "Хяналтын самбарт буцах",
    competitionManagement: "Тэмцээний Удирдлага",
    manageExistingCompetitions: "Одоо байгаа тэмцээнүүдийг удирдах",
    allCompetitions: "Бүх Тэмцээнүүд",
    createCompetition: "Тэмцээн Үүсгэх",
    hackathon2023: "Хакатон 2023",
    annualCodingCompetition: "Жил бүр болдог кодын тэмцээн",
    devSprint2025: "ДевСпринт 2025",
    rapidSoftwareDevContest: "24 цагийн хурдан программ хөгжүүлэлтийн тэмцээн",
    aiChallenge2024: "AI-ийн Сорилт 2024",
    buildInnovativeAIModels: "Шинэлэг AI загварууд бий болгох",
    viewDetails: "Дэлгэрэнгүй харах",
    backToList: "Жагсаалт руу буцах",
    createNewCompetition: "Шинэ Тэмцээн Үүсгэх",
    competitionName: "Тэмцээний Нэр",
    status: "Статус",
    description: "Тайлбар",
    startDate: "Эхлэх Огноо",
    endDate: "Дуусах Огноо",
    judgingCriteria: "Шүүхийн Шалгуур",
    addCriteria: "Шалгуур Нэмэх",
    criterionName: "Шалгуурын Нэр",
    addParticipant: "Оролцогч Нэмэх",
    addJudge: "Шүүгч Нэмэх",
    judgeName: "Шүүгчийн Нэр",
    judgeEmail: "Шүүгчийн Имэйл",
    totalWeight: "Нийт Жин: {value}%",
    totalMustBe100: "Нийт 100% байх ёстой",
    noCompetitionsYet: "Одоогоор тэмцээн байхгүй",
    getStartedCreateCompetition: "Шинэ тэмцээн үүсгэж эхэлнэ үү",
    accessDenied: "Хандалт Хориглогдсон",
    onlyAdmins: "Зөвхөн админууд энэ хуудсанд хандах боломжтой",
    invalidInput: "Хүчингүй Оролт",
    competitionNameRequired: "Тэмцээний нэр шаардлагатай",
    invalidCriteria: "Хүчингүй Шалгуур",
    criteriaNameWeightRequired: "Шалгуур бүр нэр болон 0-ээс их жинтэй байх ёстой",
    totalWeightMustBe100: "Шалгуурын нийт жин 100% байх ёстой",
    invalidDates: "Хүчингүй Огноо",
    startDateBeforeEndDate: "Эхлэх огноо дуусах огнооноос өмнө байх ёстой",
    validDatesRequired: "Хүчинтэй эхлэх болон дуусах огноо оруулна уу",
    participantNameRequired: "Оролцогчийн нэр шаардлагатай",
    judgeNameEmailRequired: "Шүүгчийн нэр болон имэйл шаардлагатай",
    invalidEmail: "Хүчинтэй имэйл хаяг оруулна уу",
    cannotRemove: "Устгах боломжгүй",
    atLeastOneCriterion: "Хамгийн багадаа нэг шалгуур шаардлагатай",
    success: "Амжилттай",
    competitionCreated: "Тэмцээн амжилттай үүсгэгдлээ!",
    competitionDeleted: "Тэмцээн амжилттай устгагдлаа!",
    error: "Алдаа",
    couldNotCreateCompetition: "Тэмцээн үүсгэж чадсангүй",
    couldNotDeleteCompetition: "Тэмцээн устгаж чадсангүй",
    confirmDelete: "Та энэ тэмцээнийг устгахдаа итгэлтэй байна уу?",
    unnamedCompetition: "Нэргүй Тэмцээн",
    unnamedParticipant: "Нэргүй Оролцогч",
    unnamedJudge: "Нэргүй Шүүгч",
    noDescription: "Тайлбар байхгүй",
    enterCompetitionName: "Тэмцээний нэр оруулна уу",
    enterDescription: "Тэмцээний тайлбар оруулна уу",
    enterParticipantName: "Оролцогчийн нэр оруулна уу",
    enterJudgeName: "Шүүгчийн нэр оруулна уу",
    enterJudgeEmail: "Шүүгчийн имэйл оруулна уу",
    enterCriterionName: "Шалгуурын нэр оруулна уу",
    deleteCompetition: "Тэмцээн устгах",
    dashboard: "Хяналтын Самбар",
    judge: "Шүүгч",
    scoreboard: "Онооны Самбар",
    competitions: "Тэмцээнүүд",
    profile: "Профайл",
    logout: "Гарах",
    toggleMenu: "Цэсийг Харуулах/Нуух",
    closeMenu: "Цэсийг Хаах",
    openMenu: "Цэсийг Нээх",
    profileImageAlt: "Профайлын Зураг",
    logoAlt: "ШүүгчХабын Лого",
    roleAdmin: "Админ",
    roleJudge: "Шүүгч",
    roleViewer: "Үзэгч",
    unknownUser: "Тодорхойгүй Хэрэглэгч",
    unknownRole: "Тодорхойгүй Дүр",
    login: "Нэвтрэх",
  },
  ja: {
    welcome: '{name}さん、おかえりなさい！',
    dashboardSubtitle: '今日のあなたのコンペティションの状況はこちらです。',
    activeCompetitions: 'アクティブなコンペティション',
    totalJudges: '総審査員数',
    submissionsToday: '今日の提出数',
    averageScore: '平均スコア',
    noCompetitions: '利用可能なコンペティションはありません。',
    selectLanguage: '言語を選択',
    retry: '再試行',
    comingSoon: 'さらに多くのダッシュボード機能が近日公開予定です！',
    participants: '参加者',
    judges: '審査員',
    ends: '終了',
    back: '戻る',
    judgePanel: '審査員パネル',
    welcomeJudge: '{name}さん、審査員へようこそ！',
    competition: 'コンペティション',
    upcoming: '近日中の',
    timeTBD: '時間未定',
    noPerformance: 'パフォーマンスなし',
    scoring: 'スコアリング',
    totalScore: '合計スコア',
    criteria_criteria1: '基準1',
    criteria_criteria2: '基準2',
    criteria_criteria3: '基準3',
    weight: 'ウェイト：{value}',
    scoreLabel: 'スコア',
    poor: '悪い',
    average: '平均',
    excellent: '優れている',
    commentsLabel: 'コメント',
    commentPlaceholder: '{criteria}に関するコメントを追加',
    clearScores: 'スコアをクリア',
    submitScores: 'スコアを送信',
    leaderboard: "リーダーボード",
    realTimeCompetitionResults: "リアルタイムの競技結果",
    live: "ライブ",
    refresh: "更新",
    selectEvent: "イベントを選択",
    progress: "進捗",
    completed: "完了",
    totalTeams: "総チーム数",
    judged: "審査済み",
    hackathon2023Rankings: "ハッカソン2023ランキング",
    devSprint2025Rankings: "デブスプリント2025ランキング",
    aiChallenge2024Rankings: "AIチャレンジ2024ランキング",
    team: "チーム",
    performance: "パフォーマンス",
    waitingForMoreTeams: "{count}チームの審査を待っています...",
    unknown: "不明",
    failedFetchCompetitions: "競技の取得に失敗しました：{status}",
    failedFetchScoreboard: "スコアボードの取得に失敗しました：{status}",
    invalidResponseFormat: "無効なレスポンス形式",
    noCompetitionsAvailable: "利用可能な競技はありません",
    noScoresAvailable: "スコアがありません",
    errorTitle: "エラー",
    unknownError: "不明なエラーが発生しました",
    backToDashboard: "ダッシュボードに戻る",
    competitionManagement: "競技管理",
    manageExistingCompetitions: "既存の競技を管理",
    allCompetitions: "すべての競技",
    createCompetition: "競技を作成",
    hackathon2023: "ハッカソン2023",
    annualCodingCompetition: "年次コーディング競技",
    devSprint2025: "デブスプリント2025",
    rapidSoftwareDevContest: "24時間高速ソフトウェア開発コンテスト",
    aiChallenge2024: "AIチャレンジ2024",
    buildInnovativeAIModels: "革新的なAIモデルを構築",
    viewDetails: "詳細を見る",
    backToList: "リストに戻る",
    createNewCompetition: "新しい競技を作成",
    competitionName: "競技名",
    status: "ステータス",
    description: "説明",
    startDate: "開始日",
    endDate: "終了日",
    judgingCriteria: "審査基準",
    addCriteria: "基準を追加",
    criterionName: "基準名",
    addParticipant: "参加者を追加",
    addJudge: "審査員を追加",
    judgeName: "審査員名",
    judgeEmail: "審査員メール",
    totalWeight: "合計ウェイト：{value}%",
    totalMustBe100: "合計は100%でなければなりません",
    noCompetitionsYet: "まだ競技がありません",
    getStartedCreateCompetition: "新しい競技を作成して始めましょう",
    accessDenied: "アクセス拒否",
    onlyAdmins: "このページには管理者のみアクセス可能です",
    invalidInput: "無効な入力",
    competitionNameRequired: "競技名が必要です",
    invalidCriteria: "無効な基準",
    criteriaNameWeightRequired: "各基準には名前と0より大きいウェイトが必要です",
    totalWeightMustBe100: "基準の合計ウェイトは100%でなければなりません",
    invalidDates: "無効な日付",
    startDateBeforeEndDate: "開始日は終了日より前でなければなりません",
    validDatesRequired: "有効な開始日と終了日を入力してください",
    participantNameRequired: "参加者名が必要です",
    judgeNameEmailRequired: "審査員名とメールが必要です",
    invalidEmail: "有効なメールアドレスを入力してください",
    cannotRemove: "削除できません",
    atLeastOneCriterion: "少なくとも1つの基準が必要です",
    success: "成功",
    competitionCreated: "競技が正常に作成されました！",
    competitionDeleted: "競技が正常に削除されました！",
    error: "エラー",
    couldNotCreateCompetition: "競技を作成できませんでした",
    couldNotDeleteCompetition: "競技を削除できませんでした",
    confirmDelete: "この競技を削除してもよろしいですか？",
    unnamedCompetition: "無名の競技",
    unnamedParticipant: "無名の参加者",
    unnamedJudge: "無名の審査員",
    noDescription: "説明がありません",
    enterCompetitionName: "競技名を入力してください",
    enterDescription: "競技の説明を入力してください",
    enterParticipantName: "参加者名を入力してください",
    enterJudgeName: "審査員名を入力してください",
    enterJudgeEmail: "審査員のメールを入力してください",
    enterCriterionName: "基準名を入力してください",
    deleteCompetition: "競技を削除",
    dashboard: "ダッシュボード",
    judge: "審査",
    scoreboard: "スコアボード",
    competitions: "競技",
    profile: "プロフィール",
    logout: "ログアウト",
    toggleMenu: "メニューを切り替え",
    closeMenu: "メニューを閉じる",
    openMenu: "メニューを開く",
    profileImageAlt: "プロフィール画像",
    logoAlt: "ジャッジハブのロゴ",
    roleAdmin: "管理者",
    roleJudge: "審査員",
    roleViewer: "閲覧者",
    unknownUser: "不明なユーザー",
    unknownRole: "不明な役割",
    login: "ログイン",
  },
};


interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (languageCode: string) => void;
  t: (key: string, params?: Record<string, string>) => string;
  getCurrentLanguage: () => Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Initialize from localStorage or default to 'en'
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('language') || 'en';
    }
    return 'en';
  });

  const setLanguage = (languageCode: string) => {
    setCurrentLanguage(languageCode);
    // Save to localStorage
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', languageCode);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let text = translations[currentLanguage]?.[key] || translations['en'][key] || key;
    if (params) {
      Object.keys(params).forEach((param) => {
        text = text.replace(`{${param}}`, params[param]);
      });
    }
    return text;
  };

  const getCurrentLanguage = (): Language => {
    return languages.find((lang) => lang.code === currentLanguage) || languages[0];
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, getCurrentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};